# Generated by Django 4.2.7 on 2024-04-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_typeuser_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('visitor', 'visitor'), ('vendor', 'vendor'), ('isk_account', 'isk_account')], default='visitor', max_length=200),
        ),
    ]
