# Generated by Django 4.2.7 on 2024-04-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_image_imgc_image_imgq_image_imgse_image_imgsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproperty',
            name='latitude',
            field=models.DecimalField(decimal_places=60, max_digits=60),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='longitude',
            field=models.DecimalField(decimal_places=60, max_digits=60),
        ),
        migrations.AlterField(
            model_name='saleproperty',
            name='latitude',
            field=models.DecimalField(decimal_places=60, max_digits=60),
        ),
        migrations.AlterField(
            model_name='saleproperty',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='saleproperty',
            name='longitude',
            field=models.DecimalField(decimal_places=60, max_digits=60),
        ),
    ]
