# Generated by Django 4.2.7 on 2024-04-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_rentalproperty_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproperty',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='saleproperty',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='saleproperty',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
